import os, sys


class CustomException():
    def __init__(self):
        pass


    